name: tgt-test
channels:
  - dglteam/label/cu116
  - defaults
dependencies:
  - python=3.9
  - dgl 
  - pip
  - pip:
    - numpy==1.22.3
    - pyrootutils==1.0.4
    - pytorch_lightning==1.7.7
    - --extra-index-url https://download.pytorch.org/whl/
    - torch==1.12.1+cu116
    - torchmetrics==0.9.2
